name: Pull request checks

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

env:
  GO_VERSION: "1.24.1"
  GO_LANG_CI_LINT_VERSION: "v1.64.6"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run linters
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GO_LANG_CI_LINT_VERSION }}

  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          go build ./...
          go test $(go list ./...)
